### ISSUE TITLE
Suggestion: function instead of class?

### ISSUE THREAD

**Issue by timreichen** [denosaurs/cache#2]
I am working with cached files in this [project](https://github.com/timreichen/Bundler) and needed a way of caching a file and all its dependencies like ```deno cache``` does by default.
I wonder if it would be a better idea to have functions to resolve the path and cache files instead of a ```Cache``` class
```ts
import { cache, resolve } from "https://deno.land/x/cache/mod.ts"
await cache("https://deno.land/std/path/mod.ts")
const filePath = resolve("https://deno.land/std/path/mod.ts") // output: /user/username/library/cache/deps/https/deno/deno-land/72ee5916977ca9d8801c801f642353d811373786e51e3d7574cca966634b4f97
```
I think this would be more _deno style_. What do you think?

**Comment by timreichen** [comment]
any news/decisions on this?

**Comment by eliassjogreen** [comment]
[0.2.6](https://github.com/denosaurs/cache/releases/tag/0.2.6) exports everything instead of `* as Cache` so all you would need to do now is:
```ts
import { cache } from "https://deno.land/x/cache/mod.ts";

const meta = await cache("https://deno.land/std/path/mod.ts");

console.log(meta.path);
```

~~We should probably rename `fetch` to `cache` to avoid naming conflicts with `fetch`.~~
